# Generated by Django 4.2.2 on 2023-06-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0002_uploadimagetest_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimagetest',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
