# Generated by Django 4.2.2 on 2023-06-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0003_uploadimagetest_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagetest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
